services:
  - type: web
    name: veralux-deployment       # 游대 Replaced with veralux-${company}
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    rootDir: .
    envVars:
      - key: DEPLOYMENT_ID
        value: brightbuild-template    # 游대 Replaced with ${id}
      - key: CONFIG_API_KEY
        value: REPLACE_THIS            # 游대 Replaced with apiKey
      - key: CONFIG_ENDPOINT
        value: https://portal.veralux.ai/api/configs
      - key: USE_REMOTE_CONFIG
        value: "true"
      - key: GDRIVE_FOLDER_ID
        value: REPLACE_THIS            # 游대 Replaced with process.env.GDRIVE_FOLDER_ID
      - key: STRIPE_SECRET_KEY
        value: REPLACE_THIS            # 游대 Optional
      - key: OPENAI_API_KEY
        value: REPLACE_THIS            # 游대 Optional
